<div id="reponse-modal" class="modal hide fade" >
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>

<?php foreach (array_values($this->listePj) as $i =>$pj) : ?>
<tr>   
    <?php /* Lien de la pièce jointe */ ?>
    <td>
        <a 
            class="file <?php echo htmlspecialchars(substr(strtolower($pj['EXTENSION_PIECEJOINTE']), 1, 3),ENT_QUOTES, 'UTF-8') ?>"
            href='<?php echo $this->url(array('controller' => 'piece-jointe', 'action' => 'get', 'id' => $this->id, 'idpj' => $pj['ID_PIECEJOINTE'], 'type' => $this->type)) ?>' <?php if ($pj['DESCRIPTION_PIECEJOINTE']): ?> title="<?php echo $pj['DESCRIPTION_PIECEJOINTE'] ?>" <?php endif ?> target='_blank' ><?php echo $pj['NOM_PIECEJOINTE'].$pj['EXTENSION_PIECEJOINTE'] ?></a>
    </td>
    
    <?php /* Description */ ?>
    <td><?php echo nl2br(str_replace("<br />", "" ,htmlspecialchars($pj['DESCRIPTION_PIECEJOINTE'],ENT_QUOTES, 'UTF-8'))) ?></td>
    
    <?php /* date de création*/ ?>
    <td>
        <?php
            $date = new Zend_Date($pj['DATE_PIECEJOINTE'], Zend_Date::DATES);
            echo $date->get( Zend_Date::DAY."/".Zend_Date::MONTH."/".Zend_Date::YEAR );
        ?>
    </td>

    <td>
        <?php if($pj['EXTENSION_PIECEJOINTE'] === '.pdf'): ?>
            <ul id="signatures-list<?php echo $i ?>">
            <?php if(isset($pj["signatures"])): ?>
                <?php foreach( $pj["signatures"] as $sig ) : ?>
                    <li id="<?php echo "sig" . $i . "_" . $sig["ID_UTILISATEUR"]?>" > 
                    <?php if(isset($sig["DATE_SIGNATURE"])): ?>
                        <span class="label label-success" style="min-width: 70px;" title="<?php echo $sig["DATE_SIGNATURE"] ?>">Signé</span>
                    <?php endif ?>

                    <?php if(!isset($sig["DATE_SIGNATURE"])):  ?>
                        <?php if($sig["ID_UTILISATEUR"] === $this->actual_id):  ?>
                            <span class="label label-warning" style="min-width: 70px; padding:none">Doit signer</span>
                        <?php else:  ?>                        
                            <span class="label label-default" style="min-width: 70px; padding:none">Doit signer</span>
                        <?php endif ?>
                    <?php endif ?>

                    
                    <?php 
                    if($sig["ID_UTILISATEUR"] === $this->actual_id)
                        echo "<strong>" . $sig["NOM_UTILISATEURINFORMATIONS"] . " " . $sig["PRENOM_UTILISATEURINFORMATIONS"] . "</strong>";
                    else
                        echo $sig["NOM_UTILISATEURINFORMATIONS"] . " " . $sig["PRENOM_UTILISATEURINFORMATIONS"];
                    ?>

                    <?php if(!isset($sig["DATE_SIGNATURE"])) :  ?>
                        <a style="float:right;" href="<?php echo $this->url(array('controller' => 'piece-jointe', 'action' => 'remove-signer', 'id' => $this->id, 'idpj' => $pj['ID_PIECEJOINTE'], 'type' => $this->type,'user_id' => $sig["ID_UTILISATEUR"])) ?>"><i class="icon-remove" title="Retirer" id="<?php echo "user" . $i . "_" . $sig["ID_UTILISATEUR"]?>"></i></a>
                    <?php endif ?>
                    
                    
                    </li>
                    
                <?php endforeach ?>
            <?php endif ?>
            </ul>


            <div class="search-utilisateurs">
                <input name="user_id" id="user-search-field<?php echo $i?>" type='text' placeholder="Ajouter un utilisateur ..." value='' />
                <div id="idpj<?php echo $i ?>" style="display:none"><?php echo $pj['ID_PIECEJOINTE'] ?></div>

            </div>


        <?php endif ?>

    </td>

    <?php /* Action*/ ?>
    <td>
        <?php if($pj['EXTENSION_PIECEJOINTE'] === '.pdf'): ?>
            
            <a class='ls-modal' data-backdrop="true" href='<?php echo $this->url(array('controller' => 'piece-jointe', 'action' => 'get-file-hash', 'id' => $this->id, 'idpj' => $pj['ID_PIECEJOINTE'], 'type' => $this->type, 'user_id' => $this->user_id)) ?>'><i class="icon-lock" title="Signer" ></i></a>

        <?php endif ?>

        <?php if($this->verrou != 1): ?>
            <a class='delete' href='/piece-jointe/delete?idpj=<?php echo htmlspecialchars($pj["ID_PIECEJOINTE"],ENT_QUOTES, 'UTF-8') ?>&type=<?php echo htmlspecialchars($this->type,ENT_QUOTES, 'UTF-8') ?>&id=<?php echo htmlspecialchars($this->id,ENT_QUOTES, 'UTF-8') ?>'>
                <i class="icon-trash" title="Supprimer"></i>
            </a>

        <?php endif ?>


	    <?php if(in_array($pj['EXTENSION_PIECEJOINTE'], array('.docx','.odt','.html','.rtf'))): ?>

		  <a href="<?php echo $this->url(array('controller' => 'piece-jointe', 'action' => 'convert', 'id' => $this->id, 'idpj' => $pj['ID_PIECEJOINTE'], 'type' => $this->type, 'nom_pj' => $pj['NOM_PIECEJOINTE'], 'extension_pj' => $pj['EXTENSION_PIECEJOINTE'])) ?>"><i class="icon-refresh"></i></a> 

	    <?php endif ?>

    </td>
</tr>
<?php endforeach ?>


<script type="text/javascript">

    // Fenetre modale de signature
    $('.ls-modal').on('click', function(e){
      e.preventDefault();
      var openingMode = "show";
      if (typeof(Storage) !== "undefined") {
        if(sessionStorage.getItem("certificat") && sessionStorage.getItem("password"))
            openingMode = "hide";
      }
      $('#reponse-modal').modal(openingMode).find('.modal-content').load($(this).attr('href'));      
      
    });


    // Mise à jour du champ de recherche d'utilisateur
     $(".search-utilisateurs input[type='text']").typeahead({
        minLength: 3,
        source: function(query, process) {
            return $.ajax({
                url: "/api/1.0/search/users",
                type: 'post',
                data: {
                    name: query,
                    limit: 100
                },
                success: function (result) {
                    utilisateurs = [];
                    $.each(result.response.results, function (i, preventionniste) {
                        utilisateurs.push("<span data-id='" + preventionniste.uid + "'>" + preventionniste.NOM_UTILISATEURINFORMATIONS + " " + preventionniste.PRENOM_UTILISATEURINFORMATIONS + "</span>");
                    });

                    process(utilisateurs);
                }
            });
        },
        highlighter: function (item) {
            libelle = $($.parseHTML(item)).last().text();
            libelle = libelle.replace( new RegExp( '(' + this.query + ')', 'gi' ), "<strong>$1</strong>" );
            html = $.parseHTML(item);
            $(html).last().text(libelle);
            html = $(html).text();
            return item.replace( item, html );
        },
        updater: function (item) {

            // Récupération du numéro de la pièce jointe
            var count = $("div[class*='search-utilisateurs']").length;
            var result = -1;
            for (var i = 0; i<count;i++) {
                if(document.contains(document.getElementById("user-search-field"+i))){
                    if($("#user-search-field"+i).val().trim() != ""){
                        result = i;
                    }
                }
            }

            //Requête AJAX
            var userID = $(item).attr('data-id');
            var ID_PJ = $("#idpj"+result).html();
            $.post(
                "<?php echo $this->url(array('controller' => 'piece-jointe', 'action' => 'add-signer', 'id' => $this->id, 'type' => $this->type)) ?>",
                {
                    user_id : userID,
                    idpj : ID_PJ
                },
                appendSignature,
                'text'
            );

            // Mise à jour du HTML
            $("#signatures-list"+result).append('<li><span class="label label-default" style="min-width: 70px; padding:none">Doit signer</span> '+item+'</li>');

            function appendSignature(data){
                console.log("Signature added");
            }
        }

    });

</script>


<style>

ul,li
{ 
    list-style-type: none;
    list-style-position:inside;
    margin:0;
    margin-bottom: :0;
}

ul li
{
    padding-top: 2px;
}

.search-utilisateurs{
    padding-top: 3px;
}

li i
{
    float: right;
}

</style>